<a href="https://colab.research.google.com/github/DevanshPatel234/FMML_Project_and_Labs/blob/main/My%20first%20minor%20lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
For string its{upper,lower,strip,split,replace}
For list its{append,extend,reverse,sort,pop}
For dictionary its{ keys,values,items,get,pop}
For  set its{add,remove,union,intersection,difference}





In [13]:
Q3 b)
import numpy as np
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
result=np.dot(matrix1,matrix2)
print(result)

[[19 22]
 [43 50]]


In [14]:
Q3 a)
import numpy as np
row1 = np.array([1, 1])
row2 = np.array([2, 2])
submatrix = np.vstack((row1, row2))
matrix = np.tile(submatrix, (5,5))
print(matrix)


[[1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]]


In [10]:
Q2
def calculate_highest_earning_female(work_hours):
    max_hours = 0
    highest_earning_female = None

    for name, hours, gender in work_hours:
        if gender == 'F' and hours > max_hours:
            max_hours = hours
            highest_earning_female = name

    if highest_earning_female is not None:
        payment = max_hours * 20
        return highest_earning_female, payment
    else:
        return "No female workers found in the list."
work_hours = [('Abby', 100, 'F'), ('Billy', 400, 'M'),
 ('Cassie', 800, 'F'), ('Maggi', 600, 'F'), ('Alex', 500, 'M'),
  ('Raj', 225, 'M'), ('Penny', 920, 'F'), ('Ben', 300, 'M')]

result = calculate_highest_earning_female(work_hours)
print(result)


('Penny', 18400)


In [9]:
Q1
def reverse_and_concatenate(A,B):
  reversed_A=A[::-1]
  result=reversed_A+B
  return result
string_A="Hello"
string_B="Students"
result=reverse_and_concatenate(string_A,string_B)
print(result)

olleHStudents
